compress_assets: off
gzip_assets: off

javascripts:
  assets:
    - dependencies/jquery-1.6.1.min.js
    - dependencies/underscore-min.js
    - dependencies/backbone-min.js
    - compiled/bootstrap/namespace.js
    - compiled/lib/*.js    
    - compiled/models/*.js
    - compiled/controllers/*.js
    - compiled/views/*.js
    - compiled/templates/*.js            
    - compiled/bootstrap/bootstrap.js